#!/bin/bash

echo "📋 Logs du backend DODO"
echo "========================"
echo ""
echo "Le backend tourne en processus: $(pgrep -f 'ts-node-dev.*backend' | head -1)"
echo ""
echo "Pour voir les logs en temps réel, vous avez plusieurs options:"
echo ""
echo "1️⃣  Terminal où vous avez lancé 'npm run dev'"
echo "   → Les logs s'affichent directement là"
echo ""
echo "2️⃣  Redémarrer le backend dans un terminal visible:"
echo "   cd /Users/anthonyhaddad/DODO/backend"
echo "   npm run dev"
echo ""
echo "3️⃣  Voir les logs récents (si redirigés vers un fichier):"
echo "   tail -f backend.log"
echo ""
echo "🔍 Logs importants à surveiller lors de la création d'une berceuse:"
echo "   - 🎵 [generateAndUploadLullaby] Checking Suno availability"
echo "   - ✅ Using Suno for generation OU ⚠️ Skipping Suno"
echo "   - ❌ Suno generation failed (si erreur)"
echo ""

